### PR TITLE
Index valid 773w, 774w and skip invalid 773w, 774w

### LINKED ISSUE #2032: 773w and 774w should include mms ids to be considered for indexing
### Expected behavior
https://github.com/pulibrary/bibdata/blob/dbba2526bcd540e754848f4dafd23279716d8036/marc_to_solr/lib/traject_config.rb#L605
and
https://github.com/pulibrary/bibdata/blob/dbba2526bcd540e754848f4dafd23279716d8036/marc_to_solr/lib/traject_config.rb#L609
should have only mmsids

### Actual behavior
https://github.com/pulibrary/bibdata/blob/dbba2526bcd540e754848f4dafd23279716d8036/marc_to_solr/lib/traject_config.rb#L605
and
https://github.com/pulibrary/bibdata/blob/dbba2526bcd540e754848f4dafd23279716d8036/marc_to_solr/lib/traject_config.rb#L609

are not filtered only to mmsids

### Impact of this bug
Record page fails to retrieve availability for constituent records because 773w and 774w do not have an mmsid.

### PR DESCRIPTION
**Pull request by christinach**
closes #2032 

I came across this while working on https://github.com/pulibrary/orangelight/issues/2696

### CODE REVIEW

File: marc_to_solr/lib/princeton_marc.rb [hunk 1]
```diff
@@ -827,3 +827,10 @@ def siku_heading?(field)
 def any_thesaurus_match?(field, thesauri)
   field.any? { |subfield| subfield.code == '2' && thesauri.include?(subfield.value) }
 end
+
+def valid_linked_fields(record, field_tag, accumulator)
+  fields = record.fields(field_tag).select { |f| f["w"] =~ /99[0-9]+6421/ }
+  fields.each do |field|
+    accumulator << field["w"].gsub(/^[^0-9]*(99[0-9]+6421).*$/, '\1')
```
Comment (christinach) [inline marc_to_solr/lib/princeton_marc.rb:834]: At some point, not sure when, 773w and 774w will have a prefix NjP.

File: marc_to_solr/lib/princeton_marc.rb [hunk 2]
```diff
@@ -827,3 +827,10 @@ def siku_heading?(field)
 def any_thesaurus_match?(field, thesauri)
   field.any? { |subfield| subfield.code == '2' && thesauri.include?(subfield.value) }
 end
+
+def valid_linked_fields(record, field_tag, accumulator)
+  fields = record.fields(field_tag).select { |f| f["w"] =~ /99[0-9]+6421/ }
```
Comment (maxkadel) [inline marc_to_solr/lib/princeton_marc.rb:832]: Can you put a comment explaining the regex? That it's differentiating between Alma-styled MMS ID, NJP prefix, and OCLC ids? (that's what I understood from checkin)

Comment (mzelesky) [reply marc_to_solr/lib/princeton_marc.rb:832]: In essence, the regex ensures that an MMS ID appears somewhere in the $w, and when a prefix is added to the MMS ID (like NjP or PUL), it'll still work. I agree it would be a good idea to have a small comment in the code.

**Comment by christinach** [comment]
@maxkadel can you please re-review?

**Review by maxkadel — APPROVED** [review]
