### PR TITLE
Handle missing full partner scsb dump files

### LINKED ISSUE #1366: [Bibdata/production] NoMethodError: undefined method `[]' for nil:NilClass
## Backtrace

    line 55 of [PROJECT_ROOT]/app/models/scsb/s3_bucket.rb: block in fetch_files
    line 54 of [PROJECT_ROOT]/app/models/scsb/s3_bucket.rb: map
    line 54 of [PROJECT_ROOT]/app/models/scsb/s3_bucket.rb: fetch_files

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/79523632)

### PR DESCRIPTION
**Pull request by hackartisan**
fixes #1366

### CODE REVIEW

File: spec/models/scsb/partner_updates_spec.rb [hunk 1]
```diff
@@ -25,30 +25,73 @@
...
-      expect(dump.dump_files.where(dump_file_type: log_file_type).length).to eq(1)
-      expect(dump.dump_files.map(&:path)).to contain_exactly(
-        File.join(scsb_file_dir, "scsbfull_cul_20210429_192300_1.xml.gz"),
-        File.join(scsb_file_dir, "scsbfull_cul_20210429_192300_2.xml.gz"),
-        File.join(scsb_file_dir, "scsbfull_nypl_20210430_015000_1.xml.gz"),
-        File.join(scsb_file_dir, "scsbfull_nypl_20210430_015000_2.xml.gz"),
-        a_string_matching(/#{scsb_file_dir}\/fixes_\d{4}_\d{2}_\d{2}.json.gz/)
-      )
+      it 'downloads, processes, and attaches just the nypl the files and adds an error message' do
+        Scsb::PartnerUpdates.full(dump: dump)
```
Comment (christinach) [inline spec/models/scsb/partner_updates_spec.rb:66]: maybe update to 'downloads, processes, attaches the nypl files and adds an error message'

**Review by christinach — CHANGES_REQUESTED** [review]

File: spec/models/scsb/partner_updates_spec.rb (hunk 1 above)
Comment (hackartisan) [reply spec/models/scsb/partner_updates_spec.rb]: fixed

**Review by christinach — APPROVED** [review]
