### PR TITLE
Ensuring that the SolrDeleter handles cases in which a HTTP network error is encountered when requesting the deleting of a batch of IDs

### LINKED ISSUE #1389: Index deletions failing from timeout errors
I ran the full scsb load and 2 incremental alma dumps on bibdata-alma-staging1. On every deletion there was a timeout error. It's very consistent.

Here's a backtrace
https://gist.github.com/hackartisan/bf7c906eb3fe871e6e8d09f3184e42b5

I ran them through the solr url that goes through the load balancer: "http://lib-solr8-staging.princeton.edu:8983/solr/catalog-alma-staging"

We need to replicate this locally and trace down what's causing the deletions to fail while every other index operation succeeds.

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Advances #1389

### CODE REVIEW

File: marc_to_solr/lib/solr_deleter.rb [hunk 1]
```diff
@@ -44,10 +46,10 @@ def delete_batch(batch)
       body = build_request_body(ids: batch)
 
       response = request_deletion(uri: uri, body: body)
-      return if response.status == 200
+      return unless response.nil? || response.status != 200
```
Comment (hackartisan) [inline marc_to_solr/lib/solr_deleter.rb:49]: maybe move this logic to a little helper method since it's used here and below. It would help readability to expand it to a full multi-line conditional.

**Review by hackartisan — CHANGES_REQUESTED** [review]
Please see one change request inline.

I think this is a good step toward ensuring the indexing continues on failed deletes.

But when indexing both scsb and alma record sets deletions failed consistently while regular indexing did not. I don't think we're ready to close #1381. I'll update it to say we need more investigation / replication.

File: marc_to_solr/lib/solr_deleter.rb (hunk 1 above)
Comment (christinach) [reply marc_to_solr/lib/solr_deleter.rb:49]: @hackartisan I think in your comment you meant to type: we are not ready to close issue #1389

**Comment by christinach** [comment]
@hackartisan I think in your comment you meant to type: we are not ready to close issue #1389 (I didn't want to edit your comment)

**Comment by hackartisan** [comment]
Yes. thanks @christinach; I fixed that typo.

**Review by christinach — APPROVED** [review]
