### PR TITLE
Availability for holdings with multiple items

### LINKED ISSUE #1644: Deep Availability Lookups are Failing
Examples:

https://catalog.princeton.edu/catalog/99125379810406421
https://catalog.princeton.edu/catalog/99125379706706421

### PR DESCRIPTION
**Pull request by hectorcorrea**
Updated the code to handle availability for holdings with multiple items. Now when all the items for the holding are available it returns "Available", it none of items for the holding are available it returns "Not Available", if some items for the holding are available and others are not it returns "Some items not available".

Fixes #1644 

Below is an example response: (http://localhost:3500/bibliographic/99125379810406421/availability.json?deep=true)

```
{
    "99125379706706421": {
        "22897390520006421": {
            "on_reserve": "N",
            "location": "firestone$res3hr",
            "label": "Firestone Library - Firestone Library - resc Firestone 3 Hr Res",
            "status_label": "Some items not available",
            "copy_number": "",
            "cdl": false,
            "temp_location": true,
            "id": "22897390520006421"
        },
        "22897520080006421": {
            "on_reserve": "N",
            "location": "firestone$res3hr",
            "label": "Firestone Library - Firestone Library - resc Firestone 3 Hr Res",
            "status_label": "Available",
            "copy_number": "50",
            "cdl": false,
            "temp_location": true,
            "id": "22897520080006421"
        }
    }
}
```

### CODE REVIEW

**Review by kevinreiss — APPROVED** [review]

File: spec/adapters/alma_adapter/availability_status_spec.rb [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+      stub_alma_holding_items(mms_id: "99125379706706421", holding_id: "ALL", filename: "99125379706706421_holding_items.json", query: "order_by=enum_a")
+      stub_alma_library(library_code: "firestone", location_code: "res3hr")
+      stub_alma_library(library_code: "firestone", location_code: "stacks")
+      stub_alma_library(library_code: "firestone", location_code: "dixn")
+      stub_alma_holding_items(mms_id: "99125378873406421", holding_id: "ALL", filename: "99125378873406421_holding_items.json", query: "order_by=enum_a")
+      stub_alma_library(library_code: "marquand", location_code: "res")
+    end
+
+    it "reports available when all items are available" do
+      bib = Alma::Bib.new("mms_id" => "99125379706706421")
```
Comment (christinach) [inline spec/adapters/alma_adapter/availability_status_spec.rb:15]: did you want to use a different json for all items be available? the one '99125379706706421_holding_items.json' which is stubbed has a variety of items statuses and you are using it in the third test

Comment (hectorcorrea) [reply spec/adapters/alma_adapter/availability_status_spec.rb:15]: No, I don't.  

The fixture in `99125379706706421` has two holdings that represent two different conditions (all available in one case, some available in the other).

Comment (christinach) [reply spec/adapters/alma_adapter/availability_status_spec.rb:15]: Thank you. I missed the 2 holdings.

**Review by christinach — APPROVED** [review]
